; M5StickCPlus2 - WiFiテザリング接続確認
;
; ビルド:   pio run
; 書き込み: pio run --target upload
; モニタ:   pio device monitor

[env:m5stick-cplus2]
platform = espressif32
board = m5stick-c
framework = arduino

build_flags =
    -DARDUINO_M5Stick_C
    -DCORE_DEBUG_LEVEL=3

upload_speed = 1500000
monitor_speed = 115200

lib_deps =
    m5stack/M5StickCPlus2
lib_ignore =
    DFRobot_GP8XXX
